name: Mensajes motivadores de Ballenita

on:
  pull_request:
    types: [opened, closed]

jobs:
  comentar_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Mensaje al abrir PR
        if: github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'te quiero, gracias por tu esfuerzo â¤ï¸'
            })

      - name: Mensaje al aceptar Merge
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Â¿ves? te lo dije, champ. ğŸ†'
            })
